async (page) => {
  const results=[];
  await page.getByRole('button',{name:'摸摸头',exact:true}).click();
  await page.locator('.preview-bubble').waitFor();results.push('pet reaction');
  await page.getByRole('button',{name:'角色衣橱 2',exact:true}).click();
  await page.getByRole('button',{name:'让它来陪我'}).click();
  await page.getByRole('button',{name:'我的伙伴',exact:true}).click();
  await page.getByRole('img',{name:'啾咪 · 动画版，逐帧动画',exact:true}).waitFor();
  const first=await page.locator('.stage-character canvas').evaluate(c=>c.toDataURL());
  await page.waitForTimeout(280);
  const second=await page.locator('.stage-character canvas').evaluate(c=>c.toDataURL());
  if(first===second)throw new Error('Sprite frames did not change');results.push('sprite playback');
  await page.getByRole('button',{name:'鼠尾草',exact:true}).click();
  await page.getByRole('spinbutton',{name:'自定义分钟'}).fill('1');
  await page.getByRole('button',{name:'开始专注',exact:true}).click();
  await page.getByRole('button',{name:'暂停一下',exact:true}).click();
  await page.getByRole('button',{name:'继续专注',exact:true}).waitFor();
  await page.reload();
  await page.getByRole('button',{name:'继续专注',exact:true}).waitFor();results.push('timer pause persistence');
  await page.getByRole('button',{name:'结束',exact:true}).click();
  await page.getByRole('button',{name:'偏好设置',exact:true}).click();
  await page.getByRole('switch',{name:'免打扰',exact:true}).click();
  await page.reload();
  await page.getByRole('button',{name:'免打扰中',exact:true}).waitFor();results.push('preferences persistence');
  await page.getByRole('button',{name:'免打扰中',exact:true}).click();
  await page.getByRole('button',{name:'角色衣橱 2',exact:true}).click();
  await page.getByLabel('选择角色图片或角色包文件').setInputFiles('public/pets/cream/portrait.png');
  await page.getByRole('heading',{name:'portrait',exact:true}).waitFor();results.push('PNG import');
  await page.getByRole('button',{name:'移除portrait',exact:true}).click();
  await page.getByRole('button',{name:'我的伙伴',exact:true}).click();
  await page.setViewportSize({width:1100,height:900});
  await page.screenshot({path:'output/playwright/home.png',fullPage:true});
  await page.getByRole('button',{name:'角色衣橱 2',exact:true}).click();
  await page.screenshot({path:'output/playwright/wardrobe.png',fullPage:true});
  await page.getByRole('button',{name:'偏好设置',exact:true}).click();
  await page.screenshot({path:'output/playwright/settings.png',fullPage:true});
  await page.setViewportSize({width:430,height:900});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  if(overflow)throw new Error('Mobile horizontal overflow');results.push('responsive settings');
  return {passed:results};
}
