async (page) => {
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.evaluate(() => localStorage.removeItem('desktop-pet-preview-v1'));
  await page.reload();
  const open = name => page.getByRole('button', { name: `给${name}改名`, exact: true }).click();
  const field = () => page.getByRole('textbox', { name: '伙伴名字', exact: true });
  const save = () => page.getByRole('button', { name: '保存名字', exact: true }).click();
  await open('豆包'); await save();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  const unchanged = await page.evaluate(() => JSON.parse(localStorage.getItem('desktop-pet-preview-v1')));
  if (Object.keys(unchanged.preferences.petNames).length) throw new Error('Saving an unchanged default created a nickname');
  await open('豆包');
  await field().fill('   '); await save();
  await page.getByText('名字需要 1–24 个字符', { exact: true }).waitFor();
  await field().fill('🐾'.repeat(25)); await save();
  await page.getByText('名字需要 1–24 个字符', { exact: true }).waitFor();
  await field().fill('  小团子 🐾  '); await field().press('Enter');
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('img', { name: '小团子 🐾，静态图片', exact: true }).waitFor();
  await open('小团子 🐾'); await field().fill('不要保存'); await field().press('Escape');
  await page.getByRole('button', { name: '给小团子 🐾改名', exact: true }).waitFor();
  await page.getByRole('button', { name: '鼠尾草', exact: true }).click();
  await page.reload();
  await page.getByRole('img', { name: '小团子 🐾，静态图片', exact: true }).waitFor();
  await page.getByRole('button', { name: '角色衣橱 2', exact: true }).click();
  await page.getByRole('heading', { name: '小团子 🐾', exact: true }).waitFor();
  await open('豆包 · 动画版'); await field().fill('Luna'); await save();
  await page.getByRole('heading', { name: 'Luna', exact: true }).waitFor();
  await page.getByRole('button', { name: '让它来陪我', exact: true }).click();
  await page.getByRole('button', { name: '我的伙伴', exact: true }).click();
  await page.getByRole('img', { name: 'Luna，逐帧动画', exact: true }).waitFor();
  await open('Luna'); await page.getByRole('button', { name: '恢复默认名', exact: true }).click();
  await page.getByRole('img', { name: '豆包 · 动画版，逐帧动画', exact: true }).waitFor();
  await page.getByRole('button', { name: '角色衣橱 2', exact: true }).click();
  await page.getByLabel('选择角色图片或角色包文件').setInputFiles('public/pets/cream/portrait.png');
  await open('portrait'); await field().fill('我的小猫');
  await page.getByText('修改默认名字', { exact: false }).click();
  await page.getByRole('textbox', { name: '默认名字', exact: true }).fill('自定默认');
  await save();
  await page.getByRole('heading', { name: '我的小猫', exact: true }).waitFor();
  await page.reload();
  await page.getByRole('img', { name: '我的小猫，静态图片', exact: true }).waitFor();
  await page.getByRole('button', { name: '角色衣橱 3', exact: true }).click();
  await page.getByRole('button', { name: '移除我的小猫', exact: true }).click();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('desktop-pet-preview-v1')));
  if (Object.keys(saved.preferences.petNames).length !== 1 || saved.preferences.petNames['doubao-static'] !== '小团子 🐾') throw new Error('Role names were not isolated or cleaned up');
  if (Object.keys(saved.preferences.petDefaultNames).length !== 0) throw new Error('Removed pet default name leaked');
  await page.getByRole('button', { name: '我的伙伴', exact: true }).click();
  await page.setViewportSize({ width: 1100, height: 900 });
  await page.waitForTimeout(4100);
  await page.screenshot({ path: 'output/playwright/renamed-home.png', fullPage: true });
  await open('小团子 🐾');
  await page.screenshot({ path: 'output/playwright/rename-dialog.png', fullPage: true });
  await field().fill('小猫'.repeat(12)); await save();
  await page.setViewportSize({ width: 430, height: 900 });
  if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('Long name caused horizontal overflow');
  await open('小猫'.repeat(12)); await page.getByRole('button', { name: '恢复默认名', exact: true }).click();
  await open('豆包');
  await page.getByText('修改默认名字', { exact: false }).click();
  await page.getByRole('textbox', { name: '默认名字', exact: true }).fill(' '); await save();
  await page.getByText('名字需要 1–24 个字符', { exact: true }).waitFor();
  await page.getByRole('textbox', { name: '默认名字', exact: true }).fill('年糕'); await save();
  await page.getByRole('img', { name: '年糕，静态图片', exact: true }).waitFor();
  await open('年糕'); await field().fill('小年糕'); await save();
  await open('小年糕'); await page.getByText('修改默认名字', { exact: false }).click();
  await page.getByRole('textbox', { name: '默认名字', exact: true }).fill('栗子'); await save();
  await page.getByRole('img', { name: '小年糕，静态图片', exact: true }).waitFor();
  await open('小年糕'); await page.getByRole('button', { name: '恢复默认名', exact: true }).click();
  await page.reload();
  await page.getByRole('img', { name: '栗子，静态图片', exact: true }).waitFor();
  await page.setViewportSize({ width: 1100, height: 900 });
  await page.screenshot({ path: 'output/playwright/renamed-home.png', fullPage: true });
  await open('栗子'); await page.getByText('修改默认名字', { exact: false }).click();
  await page.screenshot({ path: 'output/playwright/rename-dialog.png', fullPage: true });
  await page.getByRole('button', { name: '取消', exact: true }).click();
  if (errors.length) throw new Error(errors.join('\n'));
  return { passed: ['empty and overlong rejection', 'Chinese + emoji + trimming', 'Enter save and Escape cancel', 'skin and reload persistence', 'independent static/sprite names', 'restore default', 'imported pet rename and removal cleanup', '24-character mobile layout', 'editable default with validation', 'default changes preserve nickname', 'reset uses user default after reload'], pageErrors: errors.length };
}
